<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://org.apache.axis2/xsd" xmlns:ns="http://computeprice.spec.bpel.wso2.org" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" targetNamespace="http://computeprice.spec.bpel.wso2.org">
    <wsdl:documentation>ComputePriceService</wsdl:documentation>
    <wsdl:types>
        <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://computeprice.spec.bpel.wso2.org">
            <xs:element name="computePrice">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="orderId" nillable="true" type="xs:string"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="computePriceRequest">
        <wsdl:part name="parameters" element="ns:computePrice"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="ComputePriceServicePortType">
        <wsdl:operation name="computePrice">
            <wsdl:input message="ns:computePriceRequest" wsaw:Action="urn:computePrice"></wsdl:input>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ComputePriceServiceSoap11Binding" type="ns:ComputePriceServicePortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"></soap:binding>
        <wsdl:operation name="computePrice">
            <soap:operation soapAction="urn:computePrice" style="document"></soap:operation>
            <wsdl:input>
                <soap:body use="literal"></soap:body>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="ComputePriceServiceSoap12Binding" type="ns:ComputePriceServicePortType">
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"></soap12:binding>
        <wsdl:operation name="computePrice">
            <soap12:operation soapAction="urn:computePrice" style="document"></soap12:operation>
            <wsdl:input>
                <soap12:body use="literal"></soap12:body>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="ComputePriceServiceHttpBinding" type="ns:ComputePriceServicePortType">
        <http:binding verb="POST"></http:binding>
        <wsdl:operation name="computePrice">
            <http:operation location="computePrice"></http:operation>
            <wsdl:input>
                <mime:content type="text/xml" part="parameters"></mime:content>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ComputePriceService">
        <wsdl:port name="ComputePriceServiceHttpsSoap11Endpoint" binding="ns:ComputePriceServiceSoap11Binding">
            <soap:address location="http://localhost:9445/services/ComputePriceService.ComputePriceServiceHttpsSoap11Endpoint/"></soap:address>
        </wsdl:port>
        <wsdl:port name="ComputePriceServiceHttpSoap11Endpoint" binding="ns:ComputePriceServiceSoap11Binding">
            <soap:address location="http://localhost:9765/services/ComputePriceService.ComputePriceServiceHttpSoap11Endpoint/"></soap:address>
        </wsdl:port>
        <wsdl:port name="ComputePriceServiceHttpSoap12Endpoint" binding="ns:ComputePriceServiceSoap12Binding">
            <soap12:address location="http://localhost:9765/services/ComputePriceService.ComputePriceServiceHttpSoap12Endpoint/"></soap12:address>
        </wsdl:port>
        <wsdl:port name="ComputePriceServiceHttpsSoap12Endpoint" binding="ns:ComputePriceServiceSoap12Binding">
            <soap12:address location="https://localhost:9445/services/ComputePriceService.ComputePriceServiceHttpsSoap12Endpoint/"></soap12:address>
        </wsdl:port>
        <wsdl:port name="ComputePriceServiceHttpsEndpoint" binding="ns:ComputePriceServiceHttpBinding">
            <http:address location="https://localhost:9445/services/ComputePriceService.ComputePriceServiceHttpsEndpoint/"></http:address>
        </wsdl:port>
        <wsdl:port name="ComputePriceServiceHttpEndpoint" binding="ns:ComputePriceServiceHttpBinding">
            <http:address location="http://localhost:9765/services/ComputePriceService.ComputePriceServiceHttpEndpoint/"></http:address>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>